-- Full column sync: Aztec → Pangea
-- Generated by comparing OpenAPI schemas from both databases
-- Adds all columns present in Aztec but missing from Pangea

-- ============================================
-- 1. audit_log: missing changed_by_role
-- ============================================
ALTER TABLE public.audit_log ADD COLUMN IF NOT EXISTS changed_by_role TEXT;

-- ============================================
-- 2. labour_requests: missing duration_weeks, finish_reminder_sent
-- ============================================
ALTER TABLE public.labour_requests ADD COLUMN IF NOT EXISTS duration_weeks INTEGER;
ALTER TABLE public.labour_requests ADD COLUMN IF NOT EXISTS finish_reminder_sent BOOLEAN DEFAULT FALSE;

-- ============================================
-- 3. notifications: missing read_at
-- ============================================
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;

-- ============================================
-- 4. users: missing can_export, can_import
-- ============================================
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS can_export BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS can_import BOOLEAN DEFAULT FALSE;
